### ISSUE TITLE
PGML.pl has lines that should have been removed.

### ISSUE THREAD

**Issue by dpvc** [openwebwork/pg#1005]
The lines

https://github.com/openwebwork/pg/blob/832cb295f3b829c650e86ed40216bdb793c2e5c8/macros/core/PGML.pl#L942-L945

should have been removed when

https://github.com/openwebwork/pg/blob/832cb295f3b829c650e86ed40216bdb793c2e5c8/macros/core/PGML.pl#L946-L948

where added in #981.  It looks like the changes from [my suggestions](https://github.com/openwebwork/pg/issues/886#issuecomment-1843722005) that removed those lines didn't make it into the actual PR.

**Comment by pstaabp** [comment]
fixed in #1006
