### ISSUE TITLE
keyboard issue with GraphTool

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/pg#1014]
With parserGraphTool, suppose I have:

```
  bBox => [-1, 2000, 6.5, -100],
  availableTools => [ "PointTool" ],
  gridY => 100,
  ticksDistanceY => 200,
  snapSizeY => 16,
```

At this scale, I want to use the keyboard arrows to precisely place a point. But up/down is jumping me by 80 units. Should this be using snapSizeY instead?

**Comment by Alex-Jordan** [comment]
The snap size is 16 (I had typed it wrong as 6 when I first posted). I note that 80 is 16*5, so that is probably where the 80 comes from.

**Comment by drgrice1** [comment]
> At this scale, I want to use the keyboard arrows to precisely place a point. But up/down is jumping me by 80 units. Should this be using snapSizeY instead?

I am looking into this.  It looks like it might be an issue with JSXGraph that occurs when the board y range is so large.  Note that keyboard movement of points is done directly by JSXGraph, and not by code in the graphtool.

Your last comment confuses me though.  Your settings are using snapSizeY.  What do you mean by should this use snapSizeY instead?

**Comment by Alex-Jordan** [comment]
I mean that instead of jumping up by 80 each time I hit the up arrow, it should jump up by 16 (the snapSizeY).

**Comment by drgrice1** [comment]
I see.  So to answer that question then, yes, it should be jumping up by 16 not 80.

**Comment by drgrice1** [comment]
So this does seem to be a bug with JSXGraph at this scale.  Here is a minimal example that just uses JSXGraph, and nothing else.  In this example, the same thing happens.
```html
<!DOCTYPE html>
<html lang="en-US">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/jsxgraph@1.6.2/distrib/jsxgraph.min.css" media="screen">
	<script src="https://cdn.jsdelivr.net/npm/jsxgraph@1.6.2/distrib/jsxgraphcore.js"></script>
	<title>JSX Point</title>
</head>

<body>
	<div id="box" class="jxgbox" style="width:440px; height:440px"></div>

	<script>
		const b = JXG.JSXGraph.initBoard('box', {
			showCopyright: false,
			pan: {enabled: false},
			zoom: {enabled: false},
			showNavigation: false,
			boundingBox: [-1, 2000, 6.5, -100],
			grid: {gridX: 1, gridY: 100},
			keyboard: {enabled: true, dx: 1, dy: 16, panShift: false}
		});

		b.create('point', [0, 0], {snapToGrid: true, snapSizeX: 1, snapSizeY: 16});
	</script>
</body>

</html>
```
Note that to get keyboard control of the point that is graphed you need to use tab to move focus to the point.

**Comment by drgrice1** [comment]
I have some good news though.  This is fixed in version 1.7.0 of JSXGraph.  So we need to update!

**Comment by drgrice1** [comment]
Ugh.  Some bad news to go with the good.  It seems that the JSXGraph developers forgot a debugging console.log statement in the code, and so anytime you graph anything the console is flooded with messages.  I built the library from the main branch in their GitHub repository, and they have fixed it there.  So they must have noticed it after their last npm release.

Everything else with the release seems to work right though.

Hopefully they put out a patch release soon.

**Comment by Alex-Jordan** [comment]
This is all good now.
