### ISSUE TITLE
GraphTool not marking correct answers as correct

### ISSUE THREAD

**Issue by JosephMPedersen** [openwebwork/pg#1093]
When I load the example here:

https://openwebwork.github.io/pg-docs/sample-problems/Algebra/GraphToolLine.html

The answer checker will only mark the answer correct if I create the line using two particular points, in a particular order, rather than marking any two points on the line (in either order) as correct.

Also, I had to remove the line:

    [@ $gt->generateAnswerGraph @]*

Because it was causing the error:

    PG question processing error messages
    PG warning messages
    
    ------
    ---- PGML (eval 5898) 1504 ------
    ==================
    Errors parsing PGML:
    Error evaluating command: Can't locate object method "generateAnswerGraph" via package "parser::GraphTool".

**Comment by drgrice1** [comment]
That will only work with version 2.18 or newer of webwork2 and pg.  If you are using a prior version of webwork2 and pg, then you will have to write a custom grader.

**Comment by drgrice1** [comment]
The `generateAnswerGraph` method was also added in 2.18.
