### ISSUE TITLE
Feedback button for 1x1 matricies appear inside the matrix brackets.

### ISSUE THREAD

**Issue by somiaj** [openwebwork/pg#1129]
Adding this here just so it is known. Here is a test problem of different matrix sizes.

```
DOCUMENT();
loadMacros(qw(PGstandard.pl PGML.pl));

$M1 = Matrix([1]);
$M2 = Matrix([ [1], [2], [3] ]);
$M3 = Matrix([ [1, 2, 3] ]);
$M4 = Matrix([ [1, 2], [3, 4] ]);

BEGIN_PGML
[``[$M1]=``] [_]*{$M1}

[``[$M2]=``] [_]*{$M2}

[``[$M3]=``] [_]*{$M3}

[``[$M4]=``] [_]*{$M4}
END_PGML
ENDDOCUMENT();
```

Here is the feedback button for a 1x1 matrix. All the rest appear outside the last bracket.

![image](https://github.com/user-attachments/assets/c56de072-ba8c-4d1a-a07f-e30bb5d3f446)

**Comment by drgrice1** [comment]
This was fixed with #1132.
