### ISSUE TITLE
Strange behavior of checkboxes inside RadioMultiAnswer

### ISSUE THREAD

**Issue by lahvak** [openwebwork/pg#1144]
I am trying to use `CheckboxList` inside `radioMultiAnswer`.  I am not sure if it is supported, but it almost works, with one exception:

When the `CheckboxList` only has one correct choice, the correct answer does not get accepted, even though it does show the correct answer when the "Show correct answer" button is clicked.  For example, in the pg file below, in the first question labeled _Choice 1_, the correct answer is "B; Choice 1 blah", which is correctly shown when "Show correct answer" is clicked, but it is not accepted as a correct answer.

When there are more than one correct choices in the check boxes, everything works fine.

For comparison, when the checkboxes with a single correct choice are used alone, outside of the `RadioMultiAnswer`, they work fine.

```
## DESCRIPTION
## Experiements with multiple choices
## ENDDESCRIPTION

DOCUMENT();

loadMacros(
    "PGstandard.pl",    # Standard macros for PG language
    "PGML.pl",          # PGML markup and Math Objects
    "parserMultipleChoice.pl",
);

$check_choices = [
    'Choice 1 blah',
    'Choice 2 bloh',
    'Choice 3 blih'
];

$checkboxes1 = CheckboxList(
    [$check_choices],
    [@$check_choices[0]],
);

$checkboxes2 = CheckboxList(
    [$check_choices],
    [@$check_choices[0,1]],
);

$checkboxes3 = CheckboxList(
    [$check_choices],
    [@$check_choices[0,1,2]],
);

$multians1 = RadioMultiAnswer([
            ['This is a BLAH'],
            ['This is not a BLAH because (mark all that applies) %s', $checkboxes1]
        ], 1);

$multians2 = RadioMultiAnswer([
            ['This is a BLAH'],
            ['This is not a BLAH because (mark all that applies) %s', $checkboxes2]
        ], 1);

$multians3 = RadioMultiAnswer([
            ['This is a BLAH'],
            ['This is not a BLAH because (mark all that applies) %s', $checkboxes3]
        ], 1);

BEGIN_PGML
Is this a _BLAH_?

Choice 1:

[_]{$multians1}

Choice 1 and 2:

[_]{$multians2}

Choice 1 and 2 and 3:
[_]{$multians3}

Compare with:

Choice 1:

[_]{$checkboxes1}
END_PGML

ENDDOCUMENT();
```

**Comment by somiaj** [comment]
I tracked down the issue, but I don't know a proper fix. Seems that when a student selects single answer the parser assigns the student's answer the type of `String` and not `List`, so the type check fails. You can get this to work for the time by telling `RadioMultiAnswer` to not check types.

```
$multians1 = RadioMultiAnswer([
            ['This is a BLAH'],
            ['This is not a BLAH because (mark all that applies) %s', $checkboxes1]
        ], 1, checkTypes => 0);
```

The above worked in my tests, though a proper fix would be to ensure the Parser assigns a type of `List` when a single checkbox is checked in this case.

**Comment by drgrice1** [comment]
Using `checkTypes => 0` is the proper fix.  There really isn't any other way for this to work unfortunately.  This just needs to be documented somewhere.

**Comment by somiaj** [comment]
Ahh, I guess the Parser cannot tell if a string comes from a checkbox or some other input. So I guess outside of this should be documented (maybe update the POD?) there isn't an issue here, and we can close this.

**Comment by somiaj** [comment]
I am going to close this, as the issue was just missing a configuration option to allow this to work.
