### ISSUE TITLE
Currency with multiple Context()->currency->set()

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/pg#1155]
The problem below works as it is. It comes from trying to use Kenyan currency notation, with "sh" in place of the dollar sign. However if you uncomment the commented lines to replace the preceding line, there are errors and the problem does not render. The error message indicates that something expects a dollar sign to still be the currency symbol.

```
DOCUMENT();
loadMacros(qw(PGstandard.pl PGML.pl contextCurrency.pl));
Context("Currency");

Context()->currency->set(symbol=>'sh', comma => ':');
#Context()->currency->set(symbol=>'sh');
#Context()->currency->set(comma => ':'); 

$a = Compute("sh 1000");

ENDDOCUMENT();
```

**Comment by drgrice1** [comment]
Interestingly, changing the order of the `set` calls as in the following works.

```perl
DOCUMENT();
loadMacros(qw(PGstandard.pl PGML.pl contextCurrency.pl));

Context("Currency");
Context()->currency->set(comma  => ':');
Context()->currency->set(symbol => 'sh');

$a = Compute('sh 1000');

ENDDOCUMENT();
```
