### ISSUE TITLE
Gateways and Labelled Answers

### ISSUE THREAD

**Issue by goehle** [openwebwork/pg#184]
I'm getting the following error when viewing the problem pasted below on gateways, but not on standard homeworks.  

```
There is no answer evaluator for the question labeled first_answer at /opt/webwork/pg/lib/WeBWorK/PG/Translator.pm line 1218
Error in Translator.pm::process_answers: Answer first_answer:<br/>
Unrecognized evaluator type || at /opt/webwork/pg/lib/WeBWorK/PG/Translator.pm line 1242
Error in Translator.pm::process_answers: Answer first_answer:<br/>
```

from the following problem

```
DOCUMENT();
loadMacros(
        "PGbasicmacros.pl",
        "PGchoicemacros.pl",
        "PGanswermacros.pl"
);
TEXT(beginproblem(), $BR,$BBOLD, "Conditional questions example", $EBOLD, $BR,$BR);
$showPartialCorrectAnswers = 1;

$a1 = random(3,25,1);
$b1 = random(2,27,1);
$x1 = random(-11,11,1);
$a2 = $a1+5;

BEGIN_TEXT
If \( f(x) = $a1 x + $b1  \), find \( f'( $x1 ) \).
$BR $BR \{NAMED_ANS_RULE('first_answer',10) \}
$BR
END_TEXT



$ans_eval1 = num_cmp($a1);       
NAMED_ANS(first_answer => $ans_eval1);                                  

# Using named answers allows for more control.  Any unique label can be
# used for an answer.    
# (see http://webwork.math.rochester.edu/docs/docs/pglanguage/pgreference/managinganswers.html
# for more details on answer evaluator formats and on naming answers
# so that you can  refer to them later.  Look also at the pod documentation in
# PG.pl and PGbasicmacros.pl  which you can also reach at
# http://webwork.math.rochester.edu/docs/techdescription/pglanguage/index.html)

# Check to see that the first answer was answered correctly.  If it was then we
# will ask further questions.
$first_Answer = $inputs_ref->{first_answer};  # We need to know what the answer
                                                                                          # was named.
$rh_ans_hash = $ans_eval1->evaluate($first_Answer);

# warn pretty_print($rh_ans_hash);  # this is useful technique for finding errors.
                                    # When uncommented it prints out the contents of 
                                    # the ans_hash for debugging

# The output of each answer evaluator consists of a single %ans_hash with (at
# least) these entries:
#       $ans_hash{score}        -- a number between 0 and 1
#       $ans_hash{correct_ans}  -- The correct answer, as supplied by the instructor
#       $ans_hash{student_ans}  -- This is the student's answer
#       $ans_hash{ans_message}  -- Any error message, or hint provided by
#                                                          the answer evaluator.
#       $ans_hash{type}   -- A string indicating the type of answer evaluator.
#                                         -- Some examples:
#                                               'number_with_units'
#                                               'function'
#                                               'frac_number'
#                                               'arith_number'
# For more details see
# http://webwork.math.rochester.edu/docs/docs/pglanguage/pgreference/answerhashdataype.html

# If they get the first answer right, then we'll ask a second part to the
# question ...
if (1 == $rh_ans_hash->{score} ) {

        # WATCH OUT!!:  BEGIN_TEXT and END_TEXT have to be on lines by
        # themselves and left justified!!!   This means you can't indent
        # this section as you might want to. The placement of BEGIN_TEXT
        # and END_TEXT is one of the very few formatting requirements in
        # the PG language.

BEGIN_TEXT
                $PAR Right! Now
                try the second part of the problem: $PAR $HR
                If \( f(x) = $a2 x + \{$b1+5\}  \), find \( f'( x) \).
                $BR $BR \{ NAMED_ANS_RULE('SecondAnSwEr',10) \}
                $BR
END_TEXT

$ans_eval2 = num_cmp($a2);

        NAMED_ANS(SecondAnSwEr => $ans_eval2); 

}  
ENDDOCUMENT();
```

**Comment by goehle** [comment]
I tracked this down.  Its caused by the fact that the PG.pl answer checker routine `LABELED_ANS` prepends various prefixes onto all of the answer labels.  However using `NAMED_ANS_RULE` or similar things does not prepend the quiz prefix.  This is done by the label generating routines and so no quiz prefix is attached to manual labels.  I can think of a few ways to fix this
-  Make `NAMED_ANS_RULE` double check to see if the quiz prefix is there and add if its not.  This is the least impact but its a little hacky and adds an extra regexp. 
-  Make `NAMED_ANS_RULE` always add the quiz prefix and remove the quiz prefix from the label generators.  It might be possible to miss things this way and there are prefixes I dont understand (like SECTION_PREFIX).  
-  Make an internal function like `_NAMED_ANS_RULE` and have internal calls sent to that.  Then `NAMED_ANS_RULE` would only be used for manually named answers and could add the quiz prefix.  
My inclination is to go with the first one but I'm not really sold one way or the other.

**Comment by goehle** [comment]
So it turns out this problem is a little deeper than it seems.  The issue affects most things with hard coded labels in problems, i.e. NAMED_ANS_RULE, NAMED_ANS_RADIO, NAMED_POP_UP_LIST.  

After a discussion with Mike, it seems the question is do we turn these into core "private" functions which shouldnt really be used in problems and create wrappers for them which add prefixes, or do we tweak these to add prefixes and create a new set of internal functions.  Other options include just accepting the fact that certain classes of problems dont work with gateways or redoing PG so that all answer id's are hashed in such a way that we dont need prefixes at all.

**Comment by Alex-Jordan** [comment]
It's 9 years later :) I just tried this in `develop`, putting the problem into a quiz/test. There was only one answer blank, and I entered the correct answer. I clicked to grade the test, and I get this error message:

```
    Non fatal warnings. These are only displayed for users with permission to view problem debugging info.
    Use of uninitialized value $1 in concatenation (.) or string at line 558 of [PG]/macros/core/PGbasicmacros.pl
    from within main::generate_aria_label called at line 328 of [PG]/macros/core/PGbasicmacros.pl
    from within main::NAMED_ANS_RULE called at line 1 of (eval 1290)
    from within main::safe_evp called at line 1862 of [PG]/macros/core/PGbasicmacros.pl
    from within main::EV3P called at line 70 of issuePG184.pg
```

The exercise now has an additional answer blank. I added the correct answer, clicked to grade, and get the same error.

It seems that a problem like this should not be used on a test/quiz, if you have to submit once getting the first part correct in order for the second part to appear. 

Anyway, the issue now (nearing the end of 2023) is that this problem named one of the answers `SecondAnSwEr`. The `generate_aria_label` subroutine assumes that if `AnSwEr` is a substring of the name, then `AnSwEr` will be followed by some digits. And that leads to the error above where `$1` is uninitialized. I propose editing the logic in `generate_aria_label` to tweak that assumption, and then the sample problem here will work fine, and then closing this issue. FWIW, I changed the `SecondAnSwEr` in this problem code to `SecondAnSwER` and then don't get the error message. I think that confirms I diagnosed this correctly.

**Comment by drgrice1** [comment]
The problem will still not work correctly in gateway quizzes since it uses a hard coded made up answer name that lacks the quiz prefix. Furthermore, the problem has no reason at all to even use a named answer.  The comments in the problem about using named answers giving more control are utterly false.

**Comment by Alex-Jordan** [comment]
Can we close the issue? It is 9 years old and hard to tell if answer rule
handling has evolved, especially with recent work of yours. If I understand
the intent of that pg sample problem, it should now be built using
scaffold.pl.

**Comment by drgrice1** [comment]
That technique is certainly better done with scaffold.pl.

I think this issue should be closed.
