### ISSUE TITLE
AskSage is partially broken

### ISSUE THREAD

**Issue by mgage** [openwebwork/pg#209]
Hi, 

AskSage seems to have stopped working — at least when it is using the fancier WEBWORK user variable return method.

I think the code needs to be revisited — in particular I suspect there are changes on the Sage end that will make the 
communication over JSON simpler.  I’m hoping someone will see some suggestions.  

All of the relevant WeBWorK code is at https://github.com/openwebwork/pg/blob/master/lib/WeBWorK/PG/IO.pm
the function query_sage_server https://github.com/openwebwork/pg/blob/master/lib/WeBWorK/PG/IO.pm#L223
and most importantly the function AskSage https://github.com/openwebwork/pg/blob/master/lib/WeBWorK/PG/IO.pm#L259

The formatting being done in lines 273–296 return output that looks like this:

IO::askSage: We have some kind of value |{"user_variables": {"WEBWORK": {"status": "ok", "data": {"text/plain": "{'diff': [4*u*v^2*cos(2*u^2*v^2) + 2*v^2*cos(2*u*v^2) 4*u^2*v*cos(2*u^2*v^2) + 4*u*v*cos(2*u*v^2)]\n [ 4/u 4/v]\n [ 14*u*v^2 14*u^2*v],\n 'function': (sin(2*u^2*v^2) + sin(2*u*v^2), log(9*u^2*v^2) + log(6*u^2*v^2), 7*u^2*v^2)}"}, "metadata": {}}}, "success": true, "execute_reply": {"status": "ok", "execution_count": 1, "payload": [], "user_expressions": {}, "user_variables": {"WEBWORK": {"status": "ok", "data": {"text/plain": "{'diff': [4*u*v^2*cos(2*u^2*v^2) + 2*v^2*cos(2*u*v^2) 4*u^2*v*cos(2*u^2*v^2) + 4*u*v*cos(2*u*v^2)]\n [ 4/u 4/v]\n [ 14*u*v^2 14*u^2*v],\n 'function': (sin(2*u^2*v^2) + sin(2*u*v^2), log(9*u^2*v^2) + log(6*u^2*v^2), 7*u^2*v^2)}"}, "metadata": {}}}}}| returned from sage at [PG]/lib/WeBWorK/PG/IO.pm line 306
This is relatively complicated and the only part we are using is:
my $sage_WEBWORK_data = $decoded->{execute_reply}{user_variables}{WEBWORK}{data}{'application/json'};
sage_WEBWORK_data: {'diff': [4*u*v^2*cos(2*u^2*v^2) + 2*v^2*cos(2*u*v^2) 4*u^2*v*cos(2*u^2*v^2) + 4*u*v*cos(2*u*v^2)] [ 4/u 4/v] [ 14*u*v^2 14*u^2*v], 'function': (sin(2*u^2*v^2) + sin(2*u*v^2), log(9*u^2*v^2) + log(6*u^2*v^2), 7*u^2*v^2)} at [PG]/lib/WeBWorK/PG/IO.pm line 333
There is an error in this output — the value part of the key/value pairs in JSON should be
enclosed in quotes.  Trying to decode $sage_WEBWORK_data doesn’t work because decode_json
doesn’t recognize the value parts properly.  Changing the value of sage_WEBWORK_data to 

sage_WEBWORK_data: {"function":"(sin(2*u^2*v^2) + sin(2*u*v^2), log(9*u^2*v^2) + log(6*u^2*v^2), 7*u^2*v^2)","diff":"[4*u*v^2*cos(2*u^2*v^2) + 2*v^2*cos(2*u*v^2) 4*u^2*v*cos(2*u^2*v^2) + 4*u*v*cos(2*u*v^2)]\n [ 4/u 4/v]\n [ 14*u*v^2 14*u^2*v]"}

My suspicion is that the formatting done in 273-296 is being done with old-fashioned code that doesn’t measure up to stricter standards for JSON these days.  Also that there are now sage tools
that make that formatting code much simpler.

Can some you with more sage and python experience help me out with this?
A few pointers to a more recent way to encode application/json output in python/sage might
be sufficient.

A functioning (actually non-functioning) problem you can test with is at 

https://hosted2.webwork.rochester.edu/webwork2/2014_07_UR_demo/askSage/4/?effectiveUser=profa&key=av8WVLauceIMqcnOeBQEo7AOftk8p2dW&user=profa

you can use the usual profa/profa login.  The other problems in that homework set work. 

I also have a more extensive testing homework set for AskSage if you need it.

Take care,

Mike

**Comment by goehle** [comment]
Is the code you posted directly from the problem/PG?     If so then the
formulas after 'diff' and 'function' need to be quoted, and there should
not be a newline after the comma near function.
Also that entire diff function block is in double quotes, and I'm not sure
it needs to be.  There are similar issues for the next instance off
diff/function as well.

There is are some packages you can use to turn  perl hashs into json
objects, if you think that would  make things easier on the pg end.

Geoff.

**Comment by mgage** [comment]
I identified the same problem. That code is being generated by sage.  So I need some help finding the correct sage object to Json conversion.  What is puzzling is that this problem used to work.  And the other problems in the home work set do the quoting correctly.

I think I need to understand the sage conversion code better

Sent from my iPhone

On May 25, 2015, at 7:22 AM, Geoff Goehle <notifications@github.com<mailto:notifications@github.com>> wrote:

Is the code you posted directly from the problem/PG? If so then the
formulas after 'diff' and 'function' need to be quoted, and there should
not be a newline after the comma near function.
Also that entire diff function block is in double quotes, and I'm not sure
it needs to be. There are similar issues for the next instance off
diff/function as well.

There is are some packages you can use to turn perl hashs into json
objects, if you think that would make things easier on the pg end.

Geoff.

-

**Comment by goehle** [comment]
You might submit it as a sage bug.  Even if its not a bug it could spur
someone to tell you how its supposed to work. 

Geoff.
