### ISSUE TITLE
Context("Fraction") does not allow approximate answers. 

### ISSUE THREAD

**Issue by goehle** [openwebwork/pg#282]
According to the documentation in contextFraction.pl when using
Context("Fraction") students should be able to submit decimal answers. However
when using this context decimal answers are required to be exactly equal which
makes it impossible to enter fractions with repeating decimal expansions.  I
did find a problem in the wild that uses contextFraction.pl in this way.  In
Library/Rochester/setIntegrals14Substitution/csuf_in_14_1.pg with seed 1247 the
answer is -20/7, which has a repeating decimal expansion, and the problem does
not ask for a fraction answer.  I don't know what side effects there would be
(if any) of adding a tolerance to the fraction comparator.  

Test code:

```
DOCUMENT();      

loadMacros(
    'PGstandard.pl',
    'PGML.pl',
    'contextFraction.pl',
);

TEXT(beginproblem());

Context('Fraction');

$A = Fraction(1,3)->reduce;
$B = Fraction(1,2)->reduce;

BEGIN_PGML
Enter .3333333333 :
[`` [$A] = ``] [______________________]{$A} 

Enter .5 :
[`` [$B] = ``] [______________________]{$B} 
END_PGML

ENDDOCUMENT();
```

**Comment by dpvc** [comment]
You are correct; I will have to fix that.  I'll let you know when I get the chance to do that.

**Comment by Alex-Jordan** [comment]
This is the same issue as #429, and there is extended discussion there. So I'm closing this issue as part of trying to get a handle on all the open issues.
