### ISSUE TITLE
AskSage results to json

### ISSUE THREAD

**Issue by FloraHerzner** [openwebwork/pg#309]
As I am relatively new to WebWork and wanted to use AskSage, I found that the Wiki only contained one example. So I viewed IO.pm to get a better understanding and a few questions appeared to me.
They regard this bit of the code.

```python
if isinstance(o,sage.rings.integer.Integer):
                json_obj = int(o)
            elif isinstance(o,(sage.rings.real_mpfr.RealLiteral, sage.rings.real_mpfr.RealNumber)):
                json_obj = float(o)
            elif sage.modules.free_module_element.is_FreeModuleElement(o):
                json_obj = list(o)
            elif sage.matrix.matrix.is_Matrix(o):
                json_obj = [list(i) for i in o.rows()]
            elif isinstance(o, SageObject):
                json_obj = repr(o)
```

I cannot seem to understand, why these cases could not all be reduced to the last one.
If we have an integer o in sage turning it into a json as an integer and then decoding it into a perl-scalar should have the same result as turning repr(o) into a json and then decoding it into a perl-scalar.
The same seems to be true for a real number apart from the number of digits. But since the MathObject Real seems to have less digits then either of those representations, that does not seem to matter so much either.
If o is a vector both the result of list(o) and repr(o) can later be transformed into a MathObject Vector.
When a matrix is returned by my sage code the result is cannot be turned into a MathObject Matrix. As in the example in the Wiki I have to turn the matrix into its rows and then print them or fix the result of 
decode_json() decoding [list(i) for i in o.rows()] up with commas, before it can be turned in a MathObject Matrix.

I found this to be highly confusing, as I wanted to write a more detailed documentation on how to use AskSage because I thought since it is made use of a few types of json, their results of AskSage would differ, e.g. had to be written in an array depending on their type. 

Can somebody explain to me what this is used for? Or might this code be redundant? In that case I would suggest removing it to avoid future confusion.

**Comment by dpvc** [comment]
Just FYI, the MathObject Real stores the same number of digits as perl reals, but it only *displays* fewer.  It uses the `%g` format for `sprintf()` by default, which gives 6 digits of precision.  You could change that to get more (or fewer).

**Comment by FloraHerzner** [comment]
Thank you for pointing that out. So the number of digits actually differs.  repr(o) gives a higher precision than float(o). But is it nessecary to limit the number of digits for some reason?

**Comment by dpvc** [comment]
I don't believe there is any reason to limit the number.  The internal format stores about 17 digits of precision (it actually uses 54 =binary digits, and that gives 16 to 17 digits of precision in base 10, depending on the number).  So if `repr(0)` produces 17 or more, then that is the best you can do.

**Comment by heiderich** [comment]
As I understand it, this function `_webwork_safe_json` is used to as a convenience function to convert Sage objects into JSON objects that can be interpreted properly by WeBWorK. This is necessary, since the standard representations of Sage objects are not JSON compatible. For instance we have:

- For floats:

```
print float(pi)
print repr(pi)
```
returns
```
3.14159265359
pi
```

- For elements of free modules:

```
M = FreeModule(base_ring=QQ,rank=2)
v = M([1,0])
print list(v)
print repr(v)
```
returns
```
[1, 0]
(1, 0)
```
For matrices:

```
I = matrix.identity(2)
print [list(i) for i in I.rows()]
print repr(I)
```
returns
```
[[1, 0], [0, 1]]
[1 0]
[0 1]
```
So the last case handled in 
```
elif isinstance(o, SageObject):
                json_obj = repr(o)
```
seems not to cover the cases treated before.
