### ISSUE TITLE
No student answer preview generated in "limited" contexts

### ISSUE THREAD

**Issue by drdrew42** [openwebwork/pg#361]
If a student submits a response that violates the "rules" of the context, no answer preview is generated, even when clicking "preview answer". This makes it difficult for the student to ascertain whether or not they have a syntax error in entering their response, or if they need to "simplify" their answer in order to meet the requirements of the context.

I've seen this happen in the LimitedPolynomial and RationalFunction contexts - I'm sure this is not an exhaustive list.

Is there a way to prioritize the parsing of the student response (in order to generate an answer preview) before passing to the context for interpretation? Particularly in the case when a student is only attempting to preview their answer?

Attempting to preview answer when working in a LimitedPolynomial context:  
<img width="836" alt="screen shot 2018-06-13 at 3 45 37 pm" src="https://user-images.githubusercontent.com/3912882/41374341-e8248e72-6f20-11e8-9fa0-41063fa8f248.png">  
(error message thrown before preview is generated)

**Comment by dpvc** [comment]
The syntax error information is displayed in the "entered" column of the results table, but it looks like you have disabled that.  You should see

<img width="1187" alt="entered" src="https://user-images.githubusercontent.com/432782/41842989-4cd72ede-783a-11e8-858b-50ba65122071.png">

One of the consequences of disabling the entered column is that you lose these syntax high-lighted error messages.  I have never thought that disabling the entered column is a good idea for this reason.

The answer preview is a TeX-formatted field.  Moving the syntax error message there would be possible, but I don't see an easy way for you to do that without changing the core WeBWorK code.  One possible core change would be to check if there is no TeX preview, and use the entered message instead (as HTML, not TeX) in that case provided the entered column is disabled.

**Comment by dpvc** [comment]
> Is there a way to prioritize the parsing of the student response (in order to generate an answer preview) before passing to the context for interpretation? Particularly in the case when a student is only attempting to preview their answer?

No, the parsing is done in order to generate the internal representation of the expression, and it is that internal form that is used to produce the typeset output.  A syntax error prevents the internal form from being generated, so no typeset output can be generated.  While in this case, the syntax error is simply a limitation, and the expression could have been parsed by an unrestricted context, but that is not always the case.  In general, syntax errors prevent meaningful typeset output.

**Comment by Alex-Jordan** [comment]
This is no longer relevant with the removal of the response table. And in the new feedback popovers, I think the "Entered" field is always present.
