### ISSUE TITLE
answerHints option checkTypes does nothing

### ISSUE THREAD

**Issue by glennricster** [openwebwork/pg#379]
There is a typo on line 126 of the answerHints.pl file that makes the checkTypes option completely useless.  The line is:
    next if $options{checkType} && $correct->type ne $student->type;
and should be
    next if $options{checkTypes} && $correct->type ne $student->type;

**Comment by taniwallach** [comment]
Is fixed by a change included in https://github.com/openwebwork/pg/pull/476 which will be in PG 2.16.
