### ISSUE TITLE
Possible misnaming of answer blank subroutines

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/pg#392]
For example, in `parserPopUp.pl` there is:
```
204 #
205 #  Answer rule is the menu list
206 #
207 sub ans_rule {shift->MENU(0,'',@_)}
208 sub named_ans_rule {shift->MENU(0,@_)}
209 sub named_ans_rule_extension {shift->MENU(1,@_)}
```

It seems to me that here, `ans_rule` is overruling the `ans_rule` from `PGbasicmacros.pl`.  OK.

But what are `named_ans_rule` and `named_ans_rule_extension` doing? There are no subroutines by the same name in `PGbasicmacros.pl`. Instead, there are `labeled_ans_rule`, `NAMED_ANS_RULE`, and `NAMED_ANS_RULE_EXTENSION`. 

In all of `pg/macros`, `named_ans_rule` only makes an appearance where it is defined here in `parserPopUp.pl`, where it is similarly defined in `parserRadioButtons.pl`, where it is similarly defined in `parserWordCompletion.pl`, and once where it is called upon in `parserMultiAnswer.pl` (but is not defined). The same for `named_ans_rule_extension`.

All of this is raising my suspicion that these instances were supposed to be the capital letter spelling, or something like that. Or do I misunderstand what is going on here?

**Comment by dpvc** [comment]
> So these are essentially only there (right now) for the sake of `parserMultiAnswer.pl`

And also `PGML.pl`, and for creating answer arrays for matrices and other list-like MathObjects, but yes, it is for that.

**Comment by Alex-Jordan** [comment]
OK, I missed PGML using `named_ans_rule` given the way "named_ans_rule" isn't found in a search. I see it now.
