### ISSUE TITLE
UTF-8 trouble with parserPopup.pl in certain settings (may apply to other MathObjects with UTF-8 string answers)

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/pg#443]
When `parserPopUp.pl` is used with non-English UTF-8 answer strings trouble occurs in some setting:

1. "images" display mode fails to work properly: when answers are submitted - the rendering of the answers table fails and the page fails to display.
2. html2xml fails to render problems. The problem seems to be that the `<methodResponse>` data includes data like
```
<member><name>correct_ans_latex_string</name><value><string>{\verb+JUNK DELETED+}</string></value></member>
```
where I replaced the contents of the `string` block as the generated data inside `\verb` is manged.

A sample response when trying to submit an answer to such a problem with images equation display mode in use is:
```
WeBWorK error
An error occured while processing your request. For help, please send mail to this site's webmaster (techdesk@mathnet.technion.ac.il), including all of the following information as well as what what you were doing when the error occured.

Thu Dec 12 13:08:07 2019

Warning messages
Error messages
Wide character in subroutine entry at /opt/webwork/pg/lib/WeBWorK/EquationCache.pm line 89.
Call stack
The information below can help locate the source of the problem.

in WeBWorK::EquationCache::lookup called at line 271 of /opt/webwork/pg/lib/WeBWorK/PG/ImageGenerator.pm
in WeBWorK::PG::ImageGenerator::add called at line 352 of /opt/webwork/webwork2/lib/WeBWorK/Utils/AttemptsTable.pm
in WeBWorK::Utils::AttemptsTable::previewAnswer called at line 250 of /opt/webwork/webwork2/lib/WeBWorK/Utils/AttemptsTable.pm
in WeBWorK::Utils::AttemptsTable::formatAnswerRow called at line 320 of /opt/webwork/webwork2/lib/WeBWorK/Utils/AttemptsTable.pm
in WeBWorK::Utils::AttemptsTable::answerTemplate called at line 350 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Problem.pm
in WeBWorK::ContentGenerator::Problem::attemptResults called at line 1935 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Problem.pm
in WeBWorK::ContentGenerator::Problem::output_summary called at line 155 of /opt/webwork/webwork2/lib/WeBWorK/Template.pm
in WeBWorK::Template::template called at line 610 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator.pm
in WeBWorK::ContentGenerator::content called at line 374 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Problem.pm
in WeBWorK::ContentGenerator::Problem::content called at line 233 of /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator.pm
in WeBWorK::ContentGenerator::go called at line 386 of /opt/webwork/webwork2/lib/WeBWorK.pm
Request information
```

An abbreviated and redacted version of the HTML response received from an `html2xml` page which hits this error is:
```
<h2>WebworkClient Errors</h2><p>Errors: <br /> <blockquote style="color:red"><code>
not well-formed (invalid token) at line 2, column 1454, byte 1623 at /usr/lib/x86_64-linux-gnu/perl5/5.26/XML/Parser.pm line 187.
<?xml version="1.0" encoding="UTF-8"?><methodResponse>

LOTS OF XML REMOVED

</methodResponse> at /opt/webwork/webwork2/lib/WebworkClient.pm line 302.
</code></blockquote> <br /> End Errors</p>
<!DOCTYPE html>
<html lang="he" dir="rtl">
<head>
<meta charset='utf-8'>
<base href="https://URL_REMOVED">
<link rel="shortcut icon" href="/webwork2_files/images/favicon.ico"/>

LOTS OF LINES REMOVED

</head>
<body>
<div class="container-fluid">
<div class="row-fluid">
<div class="span12 problem">

        <form id="problemMainForm" class="problem-main-form" name="problemMainForm" action="https://URL_REMOVED/webwork2/html2xml" method="post">
<div id="problem_body" class="problem-content" lang="en" dir="ltr" >
                        Unable to decode problem text<br/>
xmlrpcCall to renderProblem returned no result for PATH_TO_PG_FILE_REMOVED/q02.pg



</div>

LOTS OF LINES REMOVED
</form>
</div>
</div></div>

<div id="footer">
WeBWorK &copy; 1996-2019 | host: URL_REMOVED | course: COURSE_REMOVED | format: simple | theme: math4
</div>


</body>
</html>
```

**Comment by taniwallach** [comment]
Additional notes: 

1. When MathJax is used to display equations, the "formatted" answer column contains an MathJax object which has the UTF-8 (Hebrew) text selected in the Popup displayed properly.

2. A possible root cause seems to be in `lib/Value/String.pm`:
  - It seems likely that the problem is that there is either an extra or a missing conversion to UTF-8 being applied to the string being processes before it reaches it's final destination.
  - Note also: The `quoteTeX` subroutine is triggering the use of `$self->verb($s)` whenever a UTF-8 character (or anything else not in a very short list of allowed characters is detected):
```
sub quoteTeX {
  my $self = shift; my $s = shift;
  return $self->verb($s) unless $s =~ m/^[-a-z0-9 ,.;:+=?()\[\]]*$/i;
  "\\text{$s}";
}
```
and it seems that with UTF-8 support added, many more characters could be handled by `\text{}` without the need for `\verb`. Finding the correct condition to use may be challenging.

**Comment by dpvc** [comment]
The image mode issue is due to the fact that `md5_hex()` (used in EquationCache.pm line 89) can only accept characters with numbers up to 255 (see the last section of the [MD5 documentation](https://metacpan.org/pod/distribution/Digest-MD5/MD5.pm) just above the "See Also".

One solution is to use

    my $md5 = md5_hex(utf8::is_utf8($tex) ? Encode::encode_utf8($tex) : $tex);

rather than

    my $md5 = md5_hex($tex);

at line 89.

I assume that for the `html2xml` issue, you need to convert the non-ASCII unicode characters to their `&#xXXXX;` format, so that U+1234 would become `&#x1234;`.

I do not think this is a MathObject problem *per se*.

**Comment by taniwallach** [comment]
https://github.com/openwebwork/pg/pull/466 should be fixing the issue with EquationCache.pm, while https://github.com/openwebwork/webwork2/pull/1089 should have fixed the issue with XMLRPC/html2xml.
Thus this issues seems to be resolved by the merged/in review PRs. 

I'm closing this issue.
