### ISSUE TITLE
Add a method to set the mathQuillOpts flag to disabled for an input item

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/pg#451]
Certain types of input may not be handled well by MathQuill, so it would be helpful if an input item could declare that MathQuill should not handle it. In my opinion, this is a feature needed in the long term, but is not very urgent.

Adding an option for an input item to set the `mathQuillOpts` flag to `disabled` would allow an easy method for a specific input item to avoid being handled by MathQuill when it is enabled in a course.

See: https://github.com/openwebwork/webwork2/pull/1071#issuecomment-580717220

An alternate approach, should it be difficult to enable setting this flag, would be to set a special  CSS class to trigger the bypass. As @drgrice1 explained in the reference above that would be harder to do.

**Comment by Alex-Jordan** [comment]
There is a cmp option for this now.
