### ISSUE TITLE
Disabling autocomplete in problem answer fields

### ISSUE THREAD

**Issue by mworzala** [openwebwork/pg#453]
Autocomplete is fairly frustrating when attempting to type in an answer (and being prompted previous answers). I do not believe there is any scenario where having other answers autocomplete is beneficial.

Note: I am not entirely sure this is the right repo for this, let me know if it should be moved elsewhere.

**Comment by drgrice1** [comment]
What version of WeBWorK are you using?  Autocomplete has been disabled for answer boxes in WeBWorK 2.15.  See https://github.com/openwebwork/pg/pull/423.
