### ISSUE TITLE
bug with MathObjects reduction

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/pg#455]
We've hit a bug with a reduction rule in MathObjects. Something like `-5/(-2x)` is incorrectly reducing to `5/2*x`. Here is a MWE.

```
DOCUMENT();

loadMacros(
  "PGstandard.pl",
  "MathObjects.pl",
  "PGML.pl",
);

TEXT(beginproblem());

$answer = Formula("-5/(-2 x)");
$reduced = $answer->reduce;

BEGIN_PGML

The answer is [$answer], which reduces to [$reduced].

END_PGML

ENDDOCUMENT();
```

(I'm having trouble logging in to the forum while the transition is underway, or else I might have posted this there.)

**Comment by drgrice1** [comment]
You need to do a password reset on the wiki.  After you do that you will be able to sign in to the wiki and the Moodle forums.  Go to https://webwork.maa.org/wiki/Special:PasswordReset to do this.

**Comment by mgage** [comment]
Glenn,
Do you know if the emails for password reset are being sent out by the wiki?

**Comment by drgrice1** [comment]
I am not sure.  I was hoping so.  I will look into it.

**Comment by drgrice1** [comment]
It seems that the password reset emails are not being sent (or at least received).

**Comment by dlglin** [comment]
When I request a password reset email it is sent and caught in our spam filter, likely because it came from apache@🌻.invalid (see https://github.com/openwebwork/webwork.maa.org/issues/29).

**Comment by Alex-Jordan** [comment]
This is still a bug (just tested on develop). The wiki login discussion may have distracted from the issue I reported.

**Comment by dpvc** [comment]
I have made a PR (#546) that addresses this issue.  Sorry for the long wait for it.  It has scrolled off the top of my email screen, where I don;'t often look, and so was in limbo until I cleared out some more recent items.
