### ISSUE TITLE
Possible issue in how num_points and test_at are handled in lib/Value/Formula.pm

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/pg#472]
According to the documentation at https://webwork.maa.org/wiki/Context_flags the value of `num_points` should be 
```
The number of random test points to use during function comparisons. This is in addition to any test_at points, but if test_points are given, no random points are given.
```

The generation of the test points seems to be in `lib/Value/Formula.pm`. In particular, the code in `sub compare` uses:
```
  my $points  = $l->{test_points} || $l->createRandomPoints(undef,$l->{test_at});
```
and `sub createRandomPoints` of `lib/Value/Formula.pm` seems to add the points from `test_at` into the array of points
```
    push(@{$points},@{$include});
```
before it runs a loop to add the random points, whose primary end condition is `scalar(@{$points}) < $num_points+$num_undef`.

As such, it seems that the points provided by `test_at` reduce the number of random test points used, unlike what was apparently intended. 

It seems to me that to obtain the behavior intended, the value of `$num_points` should be increased by `scalar(@{$include})` before starting the `while` loop.

@dpvc - Can you take a look?

**Comment by dpvc** [comment]
Your suggestion seems reasonable.  I would recommend incrementing the `$num_points` in this conditional

https://github.com/openwebwork/pg/blob/5083fea21171623bb649b68ecaebd03176ff9af8/lib/Value/Formula.pm#L331-L334

which is where I suspect you already intended to do it.
