### ISSUE TITLE
MathObject answers no longer accept numbers starting with a decimal

### ISSUE THREAD

**Issue by drgrice1** [openwebwork/pg#525]
This seems to be another regression introduced by https://github.com/openwebwork/pg/pull/518.

If a number starts with a decimal you get the error "Missing operand before '.'".  If you precede the decimal with a zero, it works as before.

**Comment by dpvc** [comment]
Ah, yes, that would be because the for product is now before the number pattern in the token pattern (that was to allow other tokens to begin with numbers).  I'll look into how best to resolve that.

**Comment by drgrice1** [comment]
Here is a minimal example in which this occurs (if it helps).

```perl
DOCUMENT();
loadMacros("PGstandard.pl", "MathObjects.pl", "PGML.pl");
TEXT(beginproblem());

$ans = Compute(".3333");

BEGIN_PGML
Compute [`\frac{1}{3}`].

[_______]{$ans}
END_PGML
ENDDOCUMENT();
```
This problem fails to load and gives the error "Missing operand before '.'"

**Comment by dpvc** [comment]
I made a pull request to resolve the issue.
