### ISSUE TITLE
Label recently merged PRs which should have comments about them in the WW 2.16 release notes with the new tag

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/pg#527]
To help prepare the release notes for WW 2.16... I think we should label recently merged PRs which should have comments about them in the WW 2.16 release notes with the new tag. After the draft release notes get the relevant text - the tag can be dropped.

**Comment by drgrice1** [comment]
Sounds like a good idea.  This should also be done for the webwork2 code.  There are quite a few things there that will need to be documented.
