### ISSUE TITLE
Typo in options

### ISSUE THREAD

**Issue by kmill** [openwebwork/pg#536]
Reading through the source code, I noticed that "associativity" was written as "asscoiativity" here:

https://github.com/openwebwork/pg/blob/a284c3b31a26fb316c2fa6b34246df8ba2895a3e/macros/contextPiecewiseFunction.pl#L118

This seems to be a typo given the rest of the file.  (I'm not using WeBWorK right now and I'm not depending on this being fixed -- I just thought I'd let someone know.)

**Comment by dpvc** [comment]
Thanks for pointing that out!  I've made a pull request to fix it.
