### ISSUE TITLE
Cannot submit twice in undefined set

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/pg#548]
Odd issue I just noticed.

1. Find a problem in the Library Browser.
2. Use the eyeball icon to open the problem in an Undefined_Set.
3. Submit an answer.
4. Submit an answer again, and this time, there is this message `ATTEMPT NOT ACCEPTED -- Please submit answers again (or request new version if neccessary).`

I have questions. Why is Submit an option for an Undefined_Set? Instead of just Check? And why does this response only happen on the second try? Something to do with checking the previous answer no doubt.

**Comment by dlglin** [comment]
I like having Submit as an option for an Undefined_Set.  It lets me see the messages that students get when their answer is recorded.

**Comment by drgrice1** [comment]
This has been fixed.  I am going to close this.
