### ISSUE TITLE
Future work - improved handling of units (MathQuill compatibility for units)

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/pg#554]
@mgage pointed out the need for work:
Handling of units does not work as well with MathQuill.
Needs some reconsideration of how to handle this better.

**Comment by dpvc** [comment]
The MathObject `NumberWithUnits` and `FormulaWitUnits` were a last-minute hack, and were never intended as the final solution for that in MathObjects.  They work OK, but really need to be implements within the MathObject Context properly.

**Comment by pstaabp** [comment]
This is being addressed with #614

**Comment by pstaabp** [comment]
#614 has been merged in.
