### ISSUE TITLE
contextFraction.pl issue with previous answer being `ln|6/10|` and flag `reduceConstantFunctions=>0`

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/pg#567]
Below is a sample PG problem, minimalized to demonstrate an issue. Save this problem in a set, with the open and close dates such that you can submit an answer (not just check).

If you try to submit the answer `ln|6/10|` it will be a successful submission (although probably the wrong answer since I minimialized things).

Now try to submit it again, and there are errors. In 2.15, I get pink WeBWorK warnings:
```
    Argument "|" isn't numeric in numeric ge (>=) at line 877 of [PG]/macros/contextFraction.pl
    Argument "|" isn't numeric in numeric ge (>=) at (eval 1812) line 877.
```

With 2.16, I get a more severe error screen.

```
DOCUMENT();

loadMacros(
  "PGstandard.pl",
  "MathObjects.pl",
  "PGML.pl",
  "contextFraction.pl",
);

TEXT(beginproblem());

$b = 1;
($lb,$ub) = (2,3);
Context("Fraction");
Context()->flags->set(reduceConstantFunctions=>0);
$f = Formula("1/(x+$b)")->reduce;
$frac = Fraction($ub+$b,$lb+$b);
$A = Formula("ln($frac)");

BEGIN_PGML
Evaluate the definite integral.

[``\int_{[$lb]}^{[$ub]} [$f] \, dx``]

[_]{$A}{40}

END_PGML


ENDDOCUMENT(); 
```

The errors disappear if I either do not use Fraction, or if I comment out this line: `Context()->flags->set(reduceConstantFunctions=>0);`

**Comment by drgrice1** [comment]
With webwork 2.16 I am only getting the same errors that you say you get with webwork 2.15.  Different line numbers, but the same error other than that.  Not a more severe error screen.  Still seems like it shouldn't be giving any error though.

**Comment by drgrice1** [comment]
I also noted that if you add `reduceConstants => 0` to the flags the error goes away.

**Comment by dpvc** [comment]
I have made a PR to resolve this issue.

**Comment by pstaabp** [comment]
This has been addressed.
