### ISSUE TITLE
parserRadioButtons doesn't scramble custom labels to match the order that the answers are presented

### ISSUE THREAD

**Issue by dlglin** [openwebwork/pg#581]
I want to use the functionality in parserRadioButtons.pl that allows me to scramble a subset of the answers, while giving them custom labels.  The problem is that the labels don't get reordered to match the scrambled answers.  In the code block below the first answer is always labeled "Sine", even if it is a different answer.  I also tried `labels => [["Sine", "Tangent", "Exponential"], "None of these"]`, but it doesn't look like the `labels` option can handle a nested list of arrays.

The logic here is a little weird, because if someone uses `labels=>"ABC"`, then the order of those labels should never be scrambled, but if they use custom labels then the labels should be permuted to match the scrambling of the answers.

``` perl
DOCUMENT();

loadMacros(
"PGstandard.pl",
"parserRadioButtons.pl",
);

$mc = RadioButtons(
    [[ "\( \sin(x) \)", "\( \tan(x) \)", "\( e^x \)"], "None of these" ],
    "\( e^x \)",
    labels => ["Sine", "Tangent", "Exponential", "None of these"]
    );
    
BEGIN_TEXT
Which function has a horizontal asymptote?
$BR
\{ $mc->buttons() \}
END_TEXT

$showPartialCorrectAnswers = 0;

ANS( $mc->cmp() );

ENDDOCUMENT();
```

**Comment by Alex-Jordan** [comment]
In `sub randomOrder` when it establishes the order of the options, it could also rewire the labels at that time, assuming there are custom labels. And doing it there may make it easier to coordinate the two reorderings.

**Comment by dpvc** [comment]
You can already do this by providing the labels along with the texts.  E.g., 

``` perl
$radio = RadioButtons([
  [
    {Sine => "\( \sin(x) \)"},
    {Tangent => "\( \tan(x) \)"},
    {Exponential => "\( e^x \)"}
  ],
  "None of these"],
  "Exponential");
```

See if that works for your situation.

**Comment by Alex-Jordan** [comment]
I believe this is the desired behavior. You might want to declare labels appear in a certain order and the labels are not meaningfully tied to the item content. And if you do want the labels to move around as the items randomly move around, you can do that the way Davide described.
