### ISSUE TITLE
Issue with ParserAssignment.pl

### ISSUE THREAD

**Issue by dlglin** [openwebwork/pg#607]
There is an issue with ParserAssignment.pl when a student enters an answer for which PG can't generate enough points for comparison.  This was discovered with Library/FortLewis/DiffEq/1-First-order/05-Substitution-Bernoulli/Lebl-1-5-06.pg.  A MWE is attached.

Steps to reproduce:
In one of the above problems, enter an answer that is not defined on the domain (e.g. "y=sqrt(x-5)"), and click either Preview or Submit.  Now enter a correct answer and click Submit.  You will receive the error "The evaluated answer is not an answer hash : ||.", and the answer will be marked wrong.

It looks like this has something to do with the check for equivalence to the previously submitted answer.

[ParserAssignmentMWE.pg.txt](https://github.com/openwebwork/pg/files/7340572/ParserAssignmentMWE.pg.txt)

**Comment by dlglin** [comment]
Did you try submitting a correct answer after that answer?

**Comment by drdrew42** [comment]
*sigh* -- apparently I can only read a couple sentences before my brain shuts off. 

Confirmed, will investigate.

**Comment by pstaabp** [comment]
Following up on this one.  This does fix the initial error from the OPL problem and the MWE.  

There is still the warning about not generating enough points.  I understand the issue, but what do students do with this information--except ask the instructor.   And most instructor's don't understand this.  

I think this should be closed but perhaps generate a more-helpful warning.

**Comment by pstaabp** [comment]
This has been fixed by #609 and #645
