### ISSUE TITLE
Parser Assignment Issues after PR #609

### ISSUE THREAD

**Issue by drgrice1** [openwebwork/pg#644]
I think the change in pull request #609 may still need more work.  Prior to that pull request problems like the following would work:
```perl
DOCUMENT();

loadMacros("PGstandard.pl", "MathObjects.pl", "PGML.pl", "parserAssignment.pl");

parser::Assignment->Allow;

$ans = Formula("x = 5");

BEGIN_PGML
Enter [`[$ans]`].

[_]{$ans}{10}
END_PGML

ENDDOCUMENT();
```
Prior to #609 you could enter `x=5` and it would be graded as correct.  Now it fails to parse and gives the warning `The evaluated answer is not an answer hash : ||.`

You can change `Formula` to `Compute` and this works, but it seems that it should work with both.  At least it did before.

Note that if you add what was line 357 before this pull request back before the added code then this works again.  That is insert
`$other = $other->Package("Formula")->new($self->context,$other) unless $other->isFormula;`
before the current line 360.

@drdrew42 and @dpvc:  What do you think is the correct thing here?

**Comment by pstaabp** [comment]
Fixed again.  Hopefully!
