### ISSUE TITLE
PGML list behavior can depend on extra spaces at end of lines.

### ISSUE THREAD

**Issue by somiaj** [openwebwork/pg#649]
When writing an ordered list in PGML, I notice that list counters can reset if there are extra spaces at the end of a line. Consider the following two examples:

```
DOCUMENT();
loadMacros(
   "PGstandard.pl",
   "PGML.pl",
);
TEXT(beginproblem());

BEGIN_PGML
a) First Item

    More first item stuff.
    
b) Second Item
END_PGML

ENDDOCUMENT();
```

This produces the following:

![image](https://user-images.githubusercontent.com/18082412/152409489-14ddfc42-420b-4519-bdbf-e44cf5f7770d.png)

While the following example:

```
DOCUMENT();
loadMacros(
   "PGstandard.pl",
   "PGML.pl",
);
TEXT(beginproblem());

BEGIN_PGML
a) First Item   

    More first item stuff.
    
b) Second Item
END_PGML

ENDDOCUMENT();
```

which produces the following:

![image](https://user-images.githubusercontent.com/18082412/152409932-3185b95d-9efa-491a-a769-737fbbbe1d2b.png)

The only difference is that the first item `a) First Item   ` in the second example has some extra spaces at the end of the line. Since the problem editor auto indents, I find extra spaces occasionally get added to end of lines causing unexpected behavior.

**Comment by Alex-Jordan** [comment]
PGML gives meaning to spaces at the end of lines. Two spaces at the end of a line means to force a line break. I'm not sure if 3 spaces, 4 spaces, etc. also has meaning.

So this may be a bug, or it may be a natural consequence of some feature I don't fully understand. For instance it may be that your spaces at the end of the line force a break that terminates the first list. Then "More..." is not inside any list item at all. And a new list starts with "Second ..."

In the weird situation where you _want_ a new list immediately following a first list, what should be done? Like if you want
```
a.
b.
a.
b.
```
I know it's probably absurd to want that. But the breaking mechanism would allow it.

**Comment by dpvc** [comment]
This is the documented behavior for lists (see the second to last example [here](https://webwork.maa.org/wiki/Lists_and_sub-lists_-_PGML)).  Line breaking and block ending is controlled by extra spaces at the end of the lines (this comes from Markdown, on which PGML was based).

What is happening here is that you have ended the first list due to the three spaces at the end of the "First item   ", and then the intended "More stuff is outside of the list, and is just indented.  The "a. Second item" starts a new list.  So it is exactly as Alex says.  And, yes, that would allow the list numbering that he mentions.

The three-space line ending can be used to end other structures early as well.

**Comment by somiaj** [comment]
Seems I missed that part of the documentation. And looks like it is functioning as designed. Thanks for the clarification.

Since spaces are hard to see in the editor, it becomes a bit hard to just look at a PGML code to determine what would happen. Using another character to break blocks could be useful for this, though since PGML problems already depend on this, changing behavior would have unintended consequences. Closing issue since it is working as designed.

**Comment by dpvc** [comment]
> it becomes a bit hard to just look at a PGML code to determine what would happen.

Yes, I agree that makes it hard but was used because that's Markdown's approach.  I've been thinking that a PGML 2.0 might be needed that overcomes some of the issues in the current PGML, but I doubt I'll have time to do it any time soon.  We also need a MathObjects 2.0, but that probably will never happen.  Sigh.

**Comment by Alex-Jordan** [comment]
> Since spaces are hard to see in the editor

We're using an editor that is able to syntax highlight. Without looking, I'd guess we could configure it to highlight (or underline) trailing spaces. @somiaj would you like to look into if that is possible? I am not familiar with the editor that's in use now.

**Comment by somiaj** [comment]
@Alex-Jordan The editor is called codemirror, and it appears that they do have an addon to do exactly this, show trailing white space.

<https://codemirror.net/demo/trailingspace.html>

Though so far I have been unsuccessful at adding this addon and enabling this feature in webwork. In either case this issue should be moved over there if others think it will be useful to enable this addon, since that is where the javascript files that configure the editor are located.

**Comment by somiaj** [comment]
@Alex-Jordan Okay, I figured it out, seems I need to both enable the addon and set some custom css to make it work. I was missing the css part. Here is a small preview.

![image](https://user-images.githubusercontent.com/18082412/152450942-5e2a0767-42e9-49e7-a92f-4aadd46f2e55.png)

I will move this to an issue (or pull request if I can get a few more things worked out) in webwork if you think others would like this feature in the editor.

On the side note, it appears we are also dealing with codemirror addons poorly (we have our own copy of them vs using the ones provided by codemirror), so this could be cleaned up as well.

**Comment by drgrice1** [comment]
The codemirror usage could be much improved.  If you want to work on it, that would be good.

What do you mean with the codemirror addons?  The only addon we use is the PGaddons.js file.  That is a custom addon for syntax highlighting and such for PG files.

**Comment by somiaj** [comment]
@drgrice1 from what I can tell all of the addons come with codemirror in `node_modules/codemirror/addon`, so I don't see a reason we need to keep our own version of them (which might be dated and or not include any fixes or improvements). Instead we should just load the appropriate .js scripts for the addons we wish to use. I don't think we need to keep our own copy of them in the `PGaddons.js` file.

**Comment by somiaj** [comment]
It is the `PG.js` file that contains the info for the custom syntax for PG files, that is separate than from what I can tell just copies of the addons we have enabled.

**Comment by drgrice1** [comment]
I see.  I didn't actually look at it.  I just assumed that is what it was for.  I have been meaning to look deeper at that, but haven't had time.  It is somewhat low priority for me.  Even if that is tweaked to do the best that codemirror has to offer I will still not use it myself.  I prefer a real text editor, not something in a browser.

**Comment by somiaj** [comment]
I agree that a real text editor is better, but for being able to quickly test problems when I'm writing them on a remote server, I find I end up using that editor. I just haven't set up a good way to write problems with my text editor and quickly test them.

**Comment by drgrice1** [comment]
Yeah, I am accustomed to running webwork on my local machine, and directly editing the PG files in use.  Of course, most users would not have such a setup, or even want that in general.  Just developer nuts.

I still would like to see codemirror improved, and will help with that if I find time.

**Comment by somiaj** [comment]
Turns out that the syntax highlighter should have been highlighting trailing whitespace in PGML blocks this whole time, but due to the way it was using addons, it wasn't functioning. Just moving away from the local addons to using the ones provided from codemirror has also enabled the trailing whitespace highlights inside of PGML blocks without needing any new addon. See <https://github.com/openwebwork/webwork2/pull/1577>.
