### ISSUE TITLE
Compute doesn't handle small real numbers

### ISSUE THREAD

**Issue by dlglin** [openwebwork/pg#655]
When creating a MathObject Real from a perl value that is small enough to be displayed in scientific notation, Compute gives the wrong result.

e.g. `$a = Compute(0.0000128);`

The value of $a is then stored as -1.5206.  Looking at the latex string, it is displaying `1.28e-5`, which leads me to believe that Compute is converting 0.0000128 to a string, and then parsing that string and interpreting the e as exp(1).

**Comment by dpvc** [comment]
That is exactly what it does.  Compute is for turning strings into MathObjects, and converts any other perl object to a string first before computing.  You probably want to use

```
$a = Real(0.0000128);
```

Unfortunately it is not easy to tell a number from a string in Perl, and you are not supposed to have to do so in general.  The ways to do it are not straight-forward, and most seem to be introduced in perl 5 (MathObjects predate that).

I suppose one could add check for a numeric value, but that was never the intent for `Compute()`, which was for parsing strings.

**Comment by pstaabp** [comment]
fixed in #935
