### ISSUE TITLE
MathQuill incorrectly handles roots raised to exponents.

### ISSUE THREAD

**Issue by drgrice1** [openwebwork/pg#656]
If a student types `root 3 1/6  ^4` (two spaces after the 6), then the answer submitted to webwork is `( 1/6 )^(1/3)^u`, and it should be `((1/6)^(1/3))^u`.

I am submitting this issue to remind myself to fix this when I have time.

@glarose:  Thanks for pointing this out.

Note that this is correctly dealt with if the rootsAreExponents option is false.

**Comment by drgrice1** [comment]
Another similar (but unrelated codewise) issue is the following:
Say that the answer is labeled AnSwEr0001, and so the MathQuill LaTeX answer is labeled MaThQuIlL_AnSwEr0001.  Suppose the student modifies the AnSwEr0001 value using the developer tools to be "100(e^(0.007)^(t))" and also modifies the MaThQuIlL_AnSwEr0001 value to be "100\\left(e^{0.007}^t\\right".  I say the student uses the dev tools, because as far as I can tell that is the only way to get those values into these inputs.  MathQuill doesn't output these things.  In any case if those are in there (actually only the latex answer is needed), then MathQuill parses that invalid LaTeX into "100\\left(e^{0.007t}\\right)".  It should fail to parse such LaTeX.

**Comment by pstaabp** [comment]
@drgrice1 This was fixed in openwebwork/mathquill#3 correct? If so, let's close this.

**Comment by drgrice1** [comment]
Yes it was.
