### ISSUE TITLE
substitute incorrectly handles negative numbers when reduceConstants is set to 0

### ISSUE THREAD

**Issue by dlglin** [openwebwork/pg#658]
See the attached MWE.  If reduceConstants is set to 0, when a negative number is substituted into a formula, the parentheses are removed in the LaTeX string.

e.g.
Context() -> flags -> set(reduceConstants => 0);
$f = Formula("x^2");
$g = $f->substitute(x=>-3);

The value of $g is 9, but the LaTeX string for $g is "-3^2", which causes two issues:

1. $g is displayed incorrectly (without the parentheses) when shown on screen.
2. If $g is used in a subsequent calculation, then the LaTeX string is used, which leads to incorrect values.  e.g. $g-1 evaluates to -10

[reduceConstantsIssue.pg.txt](https://github.com/openwebwork/pg/files/8155227/reduceConstantsIssue.pg.txt)

**Comment by pstaabp** [comment]
#659 now fixes this.
