### ISSUE TITLE
font-size in htdocs/js/apps/Problem/problem.scss

### ISSUE THREAD

**Issue by somiaj** [openwebwork/pg#670]
`htdocs/js/apps/Problem/problem.scss` sets font-size for `label, input[type=text], select, textarea` of 16px which has the effect of making the text for multiple choice problems (and possibly elsewhere) seem fairly large compared to the surrounding text. This to me seems to be some older styling that should be removed so the font-size is inherited from the surrounding text. Thoughts? Is this configuration needed for other aspects of problems?

![image](https://user-images.githubusercontent.com/18082412/163490918-05ba8457-25c5-433a-9e5a-5e2ebd9d8d1d.png)

**Comment by pstaabp** [comment]
fixed in #694
