### ISSUE TITLE
Error in Units: electronVolt factor

### ISSUE THREAD

**Issue by duffee** [openwebwork/pg#677]
The factor for `eV` is given as `1.60E-9` when [it should be](https://duckduckgo.com/?t=ffab&q=electron+volt+in+joules&ia=answer) `1.60E-19`

When this change is made, it would be a good opportunity to add in the larger units, `keV` and `MeV` for use in particle physics questions and perhaps `GeV` which gets used for very high energy gamma rays.

**Comment by pstaabp** [comment]
Fix merged with #690.
