### ISSUE TITLE
Solution knowl not working in homework set editor problem viewer.

### ISSUE THREAD

**Issue by somiaj** [openwebwork/pg#688]
The solution knowl is not toggleable when viewing a problem in the problem viewer in the homework set editor (when not viewing it in its own window). When I click on the solution link I get the following javascript error in the console (running firefox-esr): `Uncaught TypeError: Window.getComputedStyle: Argument 1 does not implement interface Element.` in `pg_files/js/apps/Knowls/knowl.efd4201f.min.js`.

The solution knowl works just fine when viewing the problem in its own window, and it works just fine when viewing a gateway quiz problem and the solutions are shown via the 'show solutions' checkbox in the problem viewer.

**Comment by drgrice1** [comment]
Solution knowls do work for me in the homework set editor.  This may be specific to the browser or the problem in question, so we are going to need more details.

**Comment by somiaj** [comment]
I should get in the habit of testing other browsers with javascript stuff. Works fine in chromium here too. Yet another strange javascript issue due to Debian's firefox-esr version (unsure if it is Debian or Mozilla though, I'd have to install the Mozilla's firefox-esr to debug further).

So yet again not webwork's problem.

**Comment by drgrice1** [comment]
I have tested in chrome and Firefox on Ubuntu and Android, and have no issues.

**Comment by somiaj** [comment]
Hmm, so I tested firefox-esr from Mozilla, and firefox 100 from Mozilla, and I have the same problem with both this solution knowl issue and the date picker tool (previous issue). So it is something with firefox running on debian linux and some javascript stuff. Though now unsure where to report this too. Wonder what firefox on Ubuntu is doing different than on Debian. Since it affects both the Debian package and the precompiled binary I download from Mozilla. I guess I could test the firefox from snap next. Though these are just minor issues, there is something funky with javascript on my system in some rare edge cases.

**Comment by somiaj** [comment]
Tested firefox from snapd as well, same issue. I don't know if the issue could be my server, but I'm running the rc branches WeBWorK-2.17 and PG-2.17. I have ran npm install in both htdocs directory (and get no errors). Though due to being on debian, my node is only version 12.22.5, but everything seems to work, and I don't know why this would be the issue.

It is a mystery to me. I guess if I wanted to test further, I could install a ubuntu vm, and see if I have the issue there.

**Comment by somiaj** [comment]
Tested on Ubuntu 22.04 in VM, using firefox 100 from their snap repo, and get the same issue. But the issue with the month selector in the date chooser works. Maybe it is something with my older version of node.js on my server. Either way minor issue that I can live with (and in the future I'll try to remember to test chromium when I run across strange javascript bugs).

**Comment by drgrice1** [comment]
It is actually rather unlikely to be a node issue.  Node 10 worked fine for this until another issue with npm started to cause a hang up.
