### ISSUE TITLE
parserRadioButtons does not record button labels in the past answers table

### ISSUE THREAD

**Issue by dlglin** [openwebwork/pg#708]
When using a RadioButton MathObject, the entry stored in the past answer table is always of the form "B$i", where $i is the index of the answer selected.  When submitting an answer the label of the answer that was selected is displayed, so it would be much more useful to users if the past answers showed the label as well.

**Comment by drdrew42** [comment]
This is similar to multi-select problem behavior.

For analytics purposes, problem randomization makes the existing past-answers inscrutable.

**Comment by pstaabp** [comment]
This is now fixed in #778
