### ISSUE TITLE
Delete duplicate declaration of $deg in contextTrigDegrees

### ISSUE THREAD

**Issue by duffee** [openwebwork/pg#717]
The file has a second declaration of `$deg` in **macros/contextTrigDegrees.pl** line 126 (the context::TrigDegrees::numeric2 package) which generates a warning.  It's identical to the first declaration and can be removed because the `package` keyword doesn't provide scope.

Not a pressing issue, just a TODO from #702

**Comment by dpvc** [comment]
I would recommend changing `my` to `our` and keeping both declarations.  That will make them package variables, as they seem to be intended to be.

**Comment by drgrice1** [comment]
This is done in the way that @dpvc suggests in #709.
