### ISSUE TITLE
niceTables.pl depends on PGauxiliaryFunctions.pl

### ISSUE THREAD

**Issue by dlglin** [openwebwork/pg#735]
The `DataTable` subroutine in niceTables.pl calls the `max` function, which is defined in PGauxiliaryFunctions.pl, so if a PG file loads niceTables.pl but doesn't load PGauxiliaryFunctions.pl (or PGstandard.pl, which in turn loads PGauxiliaryFunctions.pl) then any calls to DataTable will result in an error.

The easy fix is to load PGauxiliaryFunctions.pl from within the `DataTable` subroutine.  Is that the right approach?

**Comment by drgrice1** [comment]
It should not be loaded in the `DataTable` sub routine, but it should be loaded by the macro.

**Comment by pstaabp** [comment]
Fixed in #738
