### ISSUE TITLE
CORS and pg/htdocs

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/pg#766]
Recent versions (or just 2.17?) have an `htdocs` folder in `pg`. Files in here are accessed using requests that pass through `webwork2_files`, for example `https://webwork.myschool.edu/webwork2_files/node_modules/mathquill/dist/fonts/Symbola.ttf`.

First can someone explain to me how that works? Because doesn't `webwork2_files` also correspond to `webwork2/htdocs`? And if so, how can one URL Location like `https://webwork.myschool.edu/webwork2_files/` correspond to two separate folders in the file tree?

This came up because the CORS headers in the apache config that apply to the `webwork2_files` Location are not being applied to the folder tree `pg/htdocs`. For example if the url above is part of a request from another site, CORS policy will prevent access.

I added a header to the apache config for the Directory `/opt/webwork/pg/htdocs/`, and that works. But before I make a PR to adjust the distribution's apache config to cover this folder, is that the best way? Should there be a Location `pg_files` that is the corresponding location to `pg/htdocs` as `webwork2_files` is to `webwork2/htdocs`?

**Comment by drgrice1** [comment]
Also, for the develop branch you should see lines 57-63 of webwork2/conf/webwork2.mojolicious.yml.  I added that for you!

**Comment by Alex-Jordan** [comment]
I hadn't looked at develop yet. I was implicitly assuming things were close enough to the same there, but yeah now I remember you've changed a lot in this area.

No, I wouldn't do a hot fix. It's the kind of thing where someone having an issue could get advice on the forum and then edit a config file not tracked by git.

> The way the /pg_files location works is if a request is made for a file in /webwork2_files, and that file is not actually in webwork/htdocs, then a rewrite is done and it checks for the file in pg/htdocs.

Thanks for that explanation.
