### ISSUE TITLE
Generating test points for FormulaUpToConstant

### ISSUE THREAD

**Issue by drdrew42** [openwebwork/pg#776]
See https://webwork.maa.org/moodle/mod/forum/discuss.php?d=8216 for the original bug report.

## Description
When scoring a FormulaUpToConstant object with a restricted domain, the evaluation may succeed or fail depending on the choice of letter used for the constant. 

### Reproduction
To see this in action, use the following MWE, responding first with either "y" or "z" as the constant, and then try responding using any other choice of letter (upper or lower case).

```perl
DOCUMENT();      
loadMacros(
   "PGstandard.pl",
   "PGML.pl",
   "parserFormulaUpToConstant.pl"
);

$a = 8;

Context()->variables->set(x => {limits => [a+1,a+10]});
$f = Formula("1/(x*sqrt(x^2-$a^2))")->reduce();
$antiderivative = FormulaUpToConstant("1/$a * asec(x/$a)");

BEGIN_PGML

Calculate [``\int[$f]\,\mathrm dx``].

[_]{$antiderivative}

END_PGML
ENDDOCUMENT();   
```

### Diagnosis

In this MWE, the coordinates originally generated for x end up being replaced by the coordinates intended for use by the "constant" variable. But this only happens when the constant variable lexicographically precedes x, (hence success with y and z as the constant of integration in the MWE).

There is a difference in behavior dependent on the choice of letter used for the constant because the coordinates for variable names must be kept in order. As a result, I suspect that the test points are becoming "corrupted" in the `addConstants` subroutine of parserFormulaUpToConstant.pl (line 239-249). When addConstants attempts to insert extra coordinate value(s) for the additional "variable(s)" used as the constant (I'm not totally clear on `n00` and `n01`), the resulting point apparently does not consistently preserve the coordinates in the right order, ultimately causing the functional evaluation to fail for all test_points and producing the "cannot generate enough valid points" error message.

**Comment by dlglin** [comment]
Is this actually a bug, or is it a symptom of the missing $ on a in the limits?

**Comment by drdrew42** [comment]
That would explain why I couldn't find an error in the logic of `addConstant`, yes. WOOF.
