### ISSUE TITLE
niceTables.pl has confusing warning if texalignment has more columns than used.

### ISSUE THREAD

**Issue by somiaj** [openwebwork/pg#831]
Just noticed that you get a warning from `niceTables.pl` when there are extra columns defined in `texalignment` that are not used. The table outputs just fine, so the warning should probably be fixed or a better warning to help point the problem author on how to fix the warning would help. Example problem:

```
DOCUMENT();
loadMacros(
    'PGstandard.pl',
    'PGML.pl',
    'niceTables.pl',
    'PGcourse.pl'
);

$table = DataTable(
    [
        ['A', 1, 2, 3],
        ['B', 5, 6, 7],
    ],
    align => '|c|c|c|c|c|',
    horizontalrules => 1,
);


BEGIN_PGML
        [$table]*
END_PGML
ENDDOCUMENT();
```

The warning is "Use of uninitialized value $a in pattern match (m//) at line 1406 of [PG]/macros/ui/niceTables.pl."

The warning goes away if the issue with too many columns is fixed, `align => '|c|c|c|c|'.

**Comment by pstaabp** [comment]
Fixed with #832
