### ISSUE TITLE
helpLink help files are no longer working.

### ISSUE THREAD

**Issue by somiaj** [openwebwork/pg#847]
I noticed that I was getting a 404 on the help files on knowls created by helpLink.  It appears they were missing the `/pg_files/` root as part of the url.  Adding `/pg_files/` to the url fixes the problem, but I don't think is the correct fix.  Unsure why `$envir{'localHelpURL'}` is no longer including `/pg_files/` in its url (assuming this is where that info should have been stored).

Anyways here is my incorrect patch that fixes the issue.

```diff
diff --git a/macros/core/PGbasicmacros.pl b/macros/core/PGbasicmacros.pl
index 6d0ada2c4..79ae90c08 100644
--- a/macros/core/PGbasicmacros.pl
+++ b/macros/core/PGbasicmacros.pl
@@ -2735,7 +2735,7 @@ sub helpLink {
 
        # If infoRef is still '', we give up and just print plain text
        return $display_text unless ($infoRef);
-       return knowlLink($display_text, url => $envir{'localHelpURL'} . $infoRef, type => 'help');
+       return knowlLink($display_text, url => '/pg_files/' . $envir{'localHelpURL'} . $infoRef, type => 'help');
 }
 
 # This method is deprecated.  There is no hope for the problems that use it.  Java and flash are dead.
```

**Comment by drgrice1** [comment]
That is definitely the correct thing to do.

Have you updated your `site.conf` file to set `$pg_htdocs_url`?  `$pg{URLs}{localHelpURL}` is set by default in `defaults.config` to be `"$pg_htdocs_url/helpFiles"`.

**Comment by somiaj** [comment]
Thanks, that is it, I missed updating my `site.conf` for adding `$pg_htdocs_url`.  I thought it might be something like that, but didn't have time to look around.

I'll close this since it was a configuration error on my end.
