### ISSUE TITLE
GraphTool correct answer graph of line when one point is just outside viewing window

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/pg#849]
If you render the following problem, and click to show Correct Answers, it is clearly wrong.

```
DOCUMENT();

loadMacros(qw(PGstandard.pl PGML.pl parserGraphTool.pl));

$gt = GraphTool("{line, solid, (9,3), (11, 5)}");

BEGIN_PGML

[_]{$gt}

END_PGML

ENDDOCUMENT();
```

The line should have slope 1, but I see
<img width="264" alt="Screen Shot 2023-06-09 at 7 17 57 PM" src="https://github.com/openwebwork/pg/assets/4732672/c433aefb-8807-428c-938d-299572349102">

It seems that the point (11,5) has been snapped to (10,5).

Note that (11,5) is outside the viewing window, but it would not be uncommon for this to happen when generating a problem randomly. The student can still make the correct line using two points within the viewing window. I did not bother including a checker for this MWE.

I haven't searched exhaustively but I have only seen this happen when one point is only one unit outside of the viewing window.

**Comment by pstaabp** [comment]
Fixed with #850
