### ISSUE TITLE
Spacing problem with function arguments in scriptsize font

### ISSUE THREAD

**Issue by sean-fitzpatrick** [openwebwork/pg#862]
From the discussion at https://webwork.maa.org/moodle/mod/forum/discuss.php?d=8303#p20426

When a function like sin(x), cos(x), ln(x) is authored using MathObjects, WeBWorK inserts a negative thin space in the TeX passed to MathJax for rendering. For example, sin(x) becomes `\sin\!\left(x\right)`.

Usually this is fine, but not if the function is in an exponent or fraction: the negative thin space becomes too large, and the opening parenthesis overlaps with the function.

Some examples of this WeBWorK-generated MathJax can be seen at
https://opentext.uleth.ca/apex-calculus/sec_chainrule.html#exercise-366
and
https://opentext.uleth.ca/apex-calculus/sec_chainrule.html#exercise-377

The suggestion from @Alex-Jordan on the forum is to replace `\!` with `\mathopen{}`.
Some limited testing on the MathJax website suggests that `\mathopen{}` gets rid of the unwanted space for regular-sized font without causing overlap for scriptsize font.

**Comment by drgrice1** [comment]
This has already been done by @Alex-Jordan in #858 which was merged recently.

**Comment by sean-fitzpatrick** [comment]
Ah! Sorry for the duplicate. He didn't mention on the forum that he'd already submittted a PR. Maybe (like me) he hit the limit for posts in a day ;-)

**Comment by drgrice1** [comment]
He submitted the pull request after he made the comment in the forums.

**Comment by drgrice1** [comment]
Maybe we could lobby @dlglin to increase the limit on posts to the forum a bit.  I think that 10 should be safe, and still avoid the mass posts we were getting from the bots that sign in via Google.

**Comment by sean-fitzpatrick** [comment]
I'd rather wait a day to post a reply than go back to when I was waking up to 2000 new messages in my inbox!!

**Comment by sean-fitzpatrick** [comment]
But yeah, 10 might be a happy medium :-)

**Comment by drgrice1** [comment]
Yeah, at least you didn't have to delete those like @dlglin and I.  In the Moodle UI you have to do it one post at a time.  Eventually I figured out how to script it though.

**Comment by Alex-Jordan** [comment]
The PR was merged this morning. Not being 100% sure it was an acceptable fix, I was waiting to circle back to the forums about it.

**Comment by dlglin** [comment]
> Maybe we could lobby @dlglin to increase the limit on posts to the forum a bit. I think that 10 should be safe, and still avoid the mass posts we were getting from the bots that sign in via Google.

I upped it to 10 on that forum.  For some reason I set some of them to 5 and others to 10.  BTW @drgrice1 you also have the ability to change those settings.

**Comment by drgrice1** [comment]
@dlglin:  I know, but it is more fun to make it your issue!
