### ISSUE TITLE
Knowl vs MathQuill focus/blur conflict

### ISSUE THREAD

**Issue by drdrew42** [openwebwork/pg#865]
For some reason, knowls receive focus before mathquill blurs… and I am not sure why that happens — but it causes a console.error because the toolbar is listening for resize, and the toolbar isn’t being removed before the knowl resizes the content height. By the time resize is triggered, however, the mathquill has lost focus and the toolbar is gone, triggering an error from `toolbar.setPosition`. 

This can be tested by rendering a problem with mathquill and a knowl (solution, hint, or help). Place your cursor in a mathquill, then click to open a knowl without leaving the mathquill.

I confirmed this by adding `if (!answerQuill.toolbar) return;` to the beginning of `setPosition` in mqeditor.js. It’s not an elegant solution… I would think the right thing is to fix the knowls?

**Comment by drgrice1** [comment]
I am unable to reproduce this for webwork 2.18 in either Firefox or Chrome on linux.  Are you testing this in the standalone renderer?

**Comment by drgrice1** [comment]
I see.  So this is an issue when rendering in an iframe in general.  What happens is that the knowl opening causes a window resize, and that happens before the mqeditor toolbar has transitioned all the way out.

This is also only a problem with older versions of the mqeditor.  That is older as in after PG 2.17 versions but not fully updated to what is in the release candidate, and as in what the standalone render's current git submodule points to (at least for your `feature/mojo-templates` branch.  We need to update the standalone renderer's git submodule to point to the latest release candidate commit.

**Comment by drdrew42** [comment]
perfect, I'd been meaning to do that anyhow!
