### ISSUE TITLE
unecessary warning for RPC rendered problem using base64 encoding

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/pg#871]
The following are the same problem rendered via rpc, one using htm2xml, the other using render_rpc. In both cases, there is a perl warning from PGalias.pl. I suspect this was already there all along, but in 2.18, the warning is being exposed. There seems to be an assumption in PGalias.pl that there should be a sourceFilePath, but these examples use base64 encoded problems as the problemSource param. There is no sourceFilePath and that leads to this warning.

This is an issue for PTX because older books (like [here](https://spot.pcc.edu/math/orcca/ed2/html/section-variables-and-evaluating-expressions.html)) use an iframe embedding with the html2xml flavor as the src, so if they rely on a server that upgrades to 2.18, these warnings are now showing up. 

https://webwork.pcc.edu/webwork2/html2xml?courseID=orcca&userID=orcca&password=anonymous&course_password=orcca&answersSubmitted=0&showSolutions=1&displayMode=MathJax&outputformat=simple&problemSeed=2&problemSource=RE9DVU1FTlQoKTsKbG9hZE1hY3JvcygiUEdzdGFuZGFyZC5wbCIsIk1hdGhPYmplY3RzLnBsIiwiUEdNTC5wbCIsIkFuc3dlckZvcm1hdEhlbHAucGwiLCJQQ0NtYWNyb3MucGwiLCJwYXJzZXJOdW1iZXJXaXRoVW5pdHMucGwiLCJQR2NvdXJzZS5wbCIsKTtURVhUKGJlZ2lucHJvYmxlbSgpKTtsb2FkTWFjcm9zKCJQQ0NtYWNyb3MucGwiKTsKVEVYVChNT0RFUyhQVFg9PicnLEhUTUw9PnFAPGRpdiBzdHlsZT0iZGlzcGxheTpub25lOyI%2BXChcbmV3Y29tbWFuZHtcc3Vic3RpdHV0ZX1bMV17e1xjb2xvcntibHVlfXt7IzF9fX19XG5ld2NvbW1hbmR7XGFtcH17Jn1cKTwvZGl2PkApKTsKQ29udGV4dCgiTnVtZXJpYyIpOwokY2Vsc2l1c1swXSA9IE51bWJlcldpdGhVbml0cygxMCwnZGVnQycpOwokY2Vsc2l1c1sxXSA9IE51bWJlcldpdGhVbml0cygtMjYwLzksJ2RlZ0MnKTsKCkJFR0lOX1BHTUwKYS4gIElmIGEgdGVtcGVyYXR1cmUgaXMgW2A1MHteXGNpcmN9XG1hdGhybXtGfVx0ZXh0eyx9YF0gd2hhdCBpcyB0aGF0IHRlbXBlcmF0dXJlIG1lYXN1cmVkIGluIENlbHNpdXM%2FCgogICAgW0BLZXlib2FyZEluc3RydWN0aW9ucyhxP1lvdSBtYXkgdXNlIFt8ZGVnQ3xdKiBmb3IgW2Bee1xjaXJjfVxtYXRocm17Q31cdGV4dHsufWBdPylAXSoqCgogICAgW19deyRjZWxzaXVzWzBdfXsyMH0KCgphLiAgSWYgYSB0ZW1wZXJhdHVyZSBpcyBbYC0yMHteXGNpcmN9XG1hdGhybXtGfVx0ZXh0eyx9YF0gd2hhdCBpcyB0aGF0IHRlbXBlcmF0dXJlIG1lYXN1cmVkIGluIENlbHNpdXM%2FCgogICAgW0BLZXlib2FyZEluc3RydWN0aW9ucyhxP1lvdSBtYXkgdXNlIFt8ZGVnQ3xdKiBmb3IgW2Bee1xjaXJjfVxtYXRocm17Q31cdGV4dHsufWBdPylAXSoqCgogICAgW19deyRjZWxzaXVzWzFdfXsyMH0KCgoKRU5EX1BHTUwKCkJFR0lOX1BHTUxfU09MVVRJT04KYS4gIFtgXGJlZ2lue2FsaWduZWR9W3RdCiAgICAgICAgICAgICAgICBcZnJhY3s1fXs5fShGIC0gMzIpXGFtcD1cZnJhY3s1fXs5fShcc3Vic3RpdHV0ZXs1MH0gLSAzMilcXAogICAgICAgICAgICAgICAgXGFtcD1cZnJhY3s1fXs5fSgxOClcXAogICAgICAgICAgICAgICAgXGFtcD1cZnJhY3s1fXsxfSgyKVxcCiAgICAgICAgICAgICAgICBcYW1wPTEwCiAgICAgICAgICAgICAgICBcZW5ke2FsaWduZWR9CiAgICAgICAgICAgICAgICBgXQoKICAgIFNvIFtgNTB7XlxjaXJjfVxtYXRocm17Rn1gXSBpcyBlcXVhdmFsZW50IHRvIFtgMTB7XlxjaXJjfVxtYXRocm17Q31cdGV4dHsufWBdCgoKYS4gIFtgXGJlZ2lue2FsaWduZWR9W3RdCiAgICAgICAgICAgICAgICBcZnJhY3s1fXs5fShGIC0gMzIpXGFtcD1cZnJhY3s1fXs5fShcc3Vic3RpdHV0ZXstMjB9IC0gMzIpXFwKICAgICAgICAgICAgICAgIFxhbXA9XGZyYWN7NX17OX0oLTUyKVxcCiAgICAgICAgICAgICAgICBcYW1wPS1cZnJhY3syNjB9ezl9XFwKICAgICAgICAgICAgICAgIFxhbXBcYXBwcm94LTI4Ljg5CiAgICAgICAgICAgICAgICBcZW5ke2FsaWduZWR9CiAgICAgICAgICAgICAgICBgXQoKICAgIFNvIFtgLTIwe15cY2lyY31cbWF0aHJte0Z9YF0gaXMgZXF1YXZhbGVudCB0byBhYm91dCBbYC0yOC44OXteXGNpcmN9XG1hdGhybXtDfVx0ZXh0ey59YF0KCgoKRU5EX1BHTUxfU09MVVRJT04KCkVORERPQ1VNRU5UKCk7

https://webwork.pcc.edu/webwork2/render_rpc?courseID=orcca&user=orcca&passwd=orcca&answersSubmitted=0&showSolutions=1&displayMode=MathJax&outputformat=simple&problemSeed=2&problemSource=RE9DVU1FTlQoKTsKbG9hZE1hY3JvcygiUEdzdGFuZGFyZC5wbCIsIk1hdGhPYmplY3RzLnBsIiwiUEdNTC5wbCIsIkFuc3dlckZvcm1hdEhlbHAucGwiLCJQQ0NtYWNyb3MucGwiLCJwYXJzZXJOdW1iZXJXaXRoVW5pdHMucGwiLCJQR2NvdXJzZS5wbCIsKTtURVhUKGJlZ2lucHJvYmxlbSgpKTtsb2FkTWFjcm9zKCJQQ0NtYWNyb3MucGwiKTsKVEVYVChNT0RFUyhQVFg9PicnLEhUTUw9PnFAPGRpdiBzdHlsZT0iZGlzcGxheTpub25lOyI%2BXChcbmV3Y29tbWFuZHtcc3Vic3RpdHV0ZX1bMV17e1xjb2xvcntibHVlfXt7IzF9fX19XG5ld2NvbW1hbmR7XGFtcH17Jn1cKTwvZGl2PkApKTsKQ29udGV4dCgiTnVtZXJpYyIpOwokY2Vsc2l1c1swXSA9IE51bWJlcldpdGhVbml0cygxMCwnZGVnQycpOwokY2Vsc2l1c1sxXSA9IE51bWJlcldpdGhVbml0cygtMjYwLzksJ2RlZ0MnKTsKCkJFR0lOX1BHTUwKYS4gIElmIGEgdGVtcGVyYXR1cmUgaXMgW2A1MHteXGNpcmN9XG1hdGhybXtGfVx0ZXh0eyx9YF0gd2hhdCBpcyB0aGF0IHRlbXBlcmF0dXJlIG1lYXN1cmVkIGluIENlbHNpdXM%2FCgogICAgW0BLZXlib2FyZEluc3RydWN0aW9ucyhxP1lvdSBtYXkgdXNlIFt8ZGVnQ3xdKiBmb3IgW2Bee1xjaXJjfVxtYXRocm17Q31cdGV4dHsufWBdPylAXSoqCgogICAgW19deyRjZWxzaXVzWzBdfXsyMH0KCgphLiAgSWYgYSB0ZW1wZXJhdHVyZSBpcyBbYC0yMHteXGNpcmN9XG1hdGhybXtGfVx0ZXh0eyx9YF0gd2hhdCBpcyB0aGF0IHRlbXBlcmF0dXJlIG1lYXN1cmVkIGluIENlbHNpdXM%2FCgogICAgW0BLZXlib2FyZEluc3RydWN0aW9ucyhxP1lvdSBtYXkgdXNlIFt8ZGVnQ3xdKiBmb3IgW2Bee1xjaXJjfVxtYXRocm17Q31cdGV4dHsufWBdPylAXSoqCgogICAgW19deyRjZWxzaXVzWzFdfXsyMH0KCgoKRU5EX1BHTUwKCkJFR0lOX1BHTUxfU09MVVRJT04KYS4gIFtgXGJlZ2lue2FsaWduZWR9W3RdCiAgICAgICAgICAgICAgICBcZnJhY3s1fXs5fShGIC0gMzIpXGFtcD1cZnJhY3s1fXs5fShcc3Vic3RpdHV0ZXs1MH0gLSAzMilcXAogICAgICAgICAgICAgICAgXGFtcD1cZnJhY3s1fXs5fSgxOClcXAogICAgICAgICAgICAgICAgXGFtcD1cZnJhY3s1fXsxfSgyKVxcCiAgICAgICAgICAgICAgICBcYW1wPTEwCiAgICAgICAgICAgICAgICBcZW5ke2FsaWduZWR9CiAgICAgICAgICAgICAgICBgXQoKICAgIFNvIFtgNTB7XlxjaXJjfVxtYXRocm17Rn1gXSBpcyBlcXVhdmFsZW50IHRvIFtgMTB7XlxjaXJjfVxtYXRocm17Q31cdGV4dHsufWBdCgoKYS4gIFtgXGJlZ2lue2FsaWduZWR9W3RdCiAgICAgICAgICAgICAgICBcZnJhY3s1fXs5fShGIC0gMzIpXGFtcD1cZnJhY3s1fXs5fShcc3Vic3RpdHV0ZXstMjB9IC0gMzIpXFwKICAgICAgICAgICAgICAgIFxhbXA9XGZyYWN7NX17OX0oLTUyKVxcCiAgICAgICAgICAgICAgICBcYW1wPS1cZnJhY3syNjB9ezl9XFwKICAgICAgICAgICAgICAgIFxhbXBcYXBwcm94LTI4Ljg5CiAgICAgICAgICAgICAgICBcZW5ke2FsaWduZWR9CiAgICAgICAgICAgICAgICBgXQoKICAgIFNvIFtgLTIwe15cY2lyY31cbWF0aHJte0Z9YF0gaXMgZXF1YXZhbGVudCB0byBhYm91dCBbYC0yOC44OXteXGNpcmN9XG1hdGhybXtDfVx0ZXh0ey59YF0KCgoKRU5EX1BHTUxfU09MVVRJT04KCkVORERPQ1VNRU5UKCk7

**Comment by drgrice1** [comment]
Yeah, this warning most likely was happening.  You should be able to see it in the apache2 error log with webwork 2.17.

I think that what should happen is that if `probFileName` is not defined (or is the empty string), then PGalias.pm should simply not try to look in the problem directory for resources, and should only check the other auxiliary directories it searches.  That is all it is used for.  Then that warning on line 114 of PGalias.pm could be deleted.

**Comment by Alex-Jordan** [comment]
This was fixed by #877.
