### ISSUE TITLE
PGstatisticsmacros error

### ISSUE THREAD

**Issue by pstaabp** [openwebwork/pg#928]
There is an error with the `normal_prob` function in PGstatisticsmacros.pl.  

See https://webwork.maa.org/moodle/mod/forum/discuss.php?d=8361.

**Comment by Alex-Jordan** [comment]
In the post, one bad output is 22.1828.

What if that is actually something like 9.99e-5? This could be about "e"
arising from scientific/engineering notation but interpreted as Euler's
constant.

**Comment by Alex-Jordan** [comment]
This turned out to be about stringifying the "e" from scientific notation as Euler's constant. So not really an issue with PGstatisticsmacros.pl.
