### ISSUE TITLE
CheckboxList reveals the correct answers

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/pg#971]
Here is a MWE:

```
DOCUMENT();
loadMacros(qw(PGstandard.pl PGML.pl parserCheckboxList.pl));

$mc = CheckboxList(['red', 'orange', 'yellow', 'green', 'blue', 'purple'], [0,1,2]);

BEGIN_PGML

What colors are "hot"?

[_]{$mc}

END_PGML
ENDDOCUMENT();
```

Load this problem, and check all of the boxes, then submit. The feedback message will tell you exactly which ones you got wrong.

**Comment by somiaj** [comment]
Adding `$showPartialCorrectAnswers = 0;` will make it so you don't see what is incorrect.

**Comment by Alex-Jordan** [comment]
It seems like the default behavior for a question like this should be to not show this. Or else you have a situation where students can hack through it in 2 attempts.

**Comment by drgrice1** [comment]
Those messages are added by the AnswerChecker.pm.

You can set `$showPartialCorrectAnswers = 0` as @somiaj said to turn that off.  With that set, no messages will be shown and no partial credit will be given unless the answer is completely correct.

For more fine tuned control you can set the `cmp` options `showHints => 0`, `showLengthHints => 0`, and `partialCredit => 0` (there is also `showParenHints` that is related, but that have effect here).  In fact setting `$showPartialCorrectAnswers = 0` sets all of those options to 0.  For more fine tuned control you can set any of those options when `cmp` is called.  Setting `showHints => 0` will remove the messages about each answer being incorrect, but as long as `showLengthHints` is still true you will get the message "There should be fewer choices in your selection" (if all are selected as in your example).  If `showLengthHints` is false, you won't get that message either.  If `partialCredit` is true, then  partial credit is still awarded.  For your example that would be 50%.

Currently the `parserCheckboxList.pl` macro just uses the `cmp_defaults` values for these options from the `Value::List` package from which it derives.  It would be very easy to change the defaults for the `parserCheckboxList.pl` macro.  We just need to add the appropriate options to the `cmp_defaults` method defined on line 458 of that macro.  The question is, which of those three options should be true by default?   All of them?  Note that if this is done, the options can still be overridden to true by passing them to the `cmp` method.
