### ISSUE TITLE
MathQuill toolbar placement in a relatively positioned parent - bug when in an RTL course.

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/pg#988]
When an input box appears in a relatively placed element in an RTL course, the MathQuill toolbar placement is problematic.

See the sample problem file [chain01.txt](https://github.com/openwebwork/pg/files/13950308/chain01.txt) and the image below. All is OK when the course language is English, but with the course language as Hebrew the location blocks the input box.

![mq_menu_placement_issue](https://github.com/openwebwork/pg/assets/39089094/781e0813-b100-4db8-a87f-ce1d4e21218b)

Related to the code at https://github.com/openwebwork/pg/blob/daff8afd342f06d25feb87d4c00280980492e318/htdocs/js/MathQuill/mqeditor.js#L362C9-L362C23

@drgrice1 Could you help with this? It seems the JavaScript code will need to condition how it calculates placement for these cases depending on whether the primary document direction is LTR (default) or RTL.

From `simple.conf`:
```
$language = 'he-IL';
$perProblemLangAndDirSettingMode = 'auto:en:ltr';
```
where dropping the language line gets placement to work.

---

Note: The problem triggers a warning. `Use of uninitialized value $html_attribs in concatenation (.) or string at line 1794 of [PG]/macros/core/PGbasicmacros.pl` A fix is below. Eventually I'll get a PR in.

---

```
diff --git a/macros/core/PGbasicmacros.pl b/macros/core/PGbasicmacros.pl
index 793e7b0c..3aeb3b55 100644
--- a/macros/core/PGbasicmacros.pl
+++ b/macros/core/PGbasicmacros.pl
@@ -1773,7 +1773,7 @@ sub openDivSpan {
                return ();
        }
        my $option_ref = {};
-       my $html_attribs;
+       my $html_attribs = '';
        if (ref($_[0]) eq 'HASH') {
                $option_ref   = shift;
                $html_attribs = processDivSpanOptions($option_ref);


```

**Comment by drgrice1** [comment]
The quick and easy solution is to add `/*rtl:ignore*/` above line 104 of `mqeditor.scss` (before `right: 10px`).  That will make the toolbar appear on the right side of the page just as it does for left-to-right languages.

**Comment by taniwallach** [comment]
Will be resolved by https://github.com/openwebwork/pg/pull/989
